all: program
clear: clean

program: String.o tests.o
	g++ -std=c++0x String.o tests.o -o tests

String.o:	String.cpp
	g++ -std=c++0x -c String.cpp -Wall

tests.o: tests.cpp
	g++ -std=c++0x -c tests.cpp -Wall

clean:
	erase *.o tests.exe 